### ISSUE TITLE
Add cmds to upload to Triton Private Cloud

### ISSUE THREAD

**Issue by JamesOBenson** [omniosorg/lx-images#4]
It would be great if you could add to the readme, how to import the files from 'release' into Triton Private Cloud for use.

**Comment by oetiker** [comment]
Hi Jan, I think joyent are actually in the process of porting this to their system ...

**Comment by teutat3s** [comment]
Just in case someone stumbles over this, this is the repo where current development of the import process seems to take place: https://github.com/TritonDataCenter/smartos-lx-img-builder
